# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.java.installations.auto-download=true

# Mod Properties
mod_version = 1.0.2
_mod_update_name = +floordrops +hideon +duplico +rockmite mound
maven_group = com.safari
archives_base_name = safari-mod

# Dependencies
minecraft_version = 26.1.2
loader_version = 0.19.3

# API Version
fabric_version = 0.155.2+26.1.2
fabric_api_version=0.155.2+26.1.2